version: '3.1'

services:
  springboot:
    image: dockerhandson/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springnetwork
 mongo:
    image: mongo
    volumes:
      - mongodatadb:/data/db
    restart: always
    networks:
    - springnetwork
   
 volumes:
  mongodatadb:
    driver: local
    
networks:
  springnetwork:
    driver: bridge
